### ISSUE TITLE
Failed to initialize the sbt project: sbt-wrapper-gen 1.0.6-SNAPSHOT not found

### ISSUE THREAD

**Issue by NomadBlacky** [j5ik2o/reactive-aws-clients#38]
I'm trying to set up this project.  
However, the sbt project initialization failed because `sbt-wrapper-gen;1.0.6-SNAPSHOT` was not found.

```
$ sbt
[info] Loading settings for project global-plugins from idea.sbt,build.sbt ...
[info] Loading global plugins from /home/blacky/.sbt/1.0/plugins
[info] Loading settings for project reactive-aws-clients-build from plugins.sbt ...
[info] Loading project definition from /home/blacky/projects/scala/reactive-aws-clients/project
[info] Updating ProjectRef(uri("file:/home/blacky/projects/scala/reactive-aws-clients/project/"), "reactive-aws-clients-build")...
[warn]  module not found: com.github.j5ik2o#sbt-wrapper-gen;1.0.6-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.github.j5ik2o/sbt-wrapper-gen/scala_2.12/sbt_1.0/1.0.6-SNAPSHOT/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.j5ik2o/sbt-wrapper-gen/scala_2.12/sbt_1.0/1.0.6-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/blacky/.ivy2/local/com.github.j5ik2o/sbt-wrapper-gen/scala_2.12/sbt_1.0/1.0.6-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/j5ik2o/sbt-wrapper-gen_2.12_1.0/1.0.6-SNAPSHOT/sbt-wrapper-gen-1.0.6-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/blacky/.sbt/preloaded/com.github.j5ik2o/sbt-wrapper-gen/1.0.6-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/blacky/.sbt/preloaded/com/github/j5ik2o/sbt-wrapper-gen_2.12_1.0/1.0.6-SNAPSHOT/sbt-wrapper-gen-1.0.6-SNAPSHOT.pom
[warn] ==== Seasar Repository: tried
[warn]   http://maven.seasar.org/maven2/com/github/j5ik2o/sbt-wrapper-gen_2.12_1.0/1.0.6-SNAPSHOT/sbt-wrapper-gen-1.0.6-SNAPSHOT.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/github/j5ik2o/sbt-wrapper-gen_2.12_1.0/1.0.6-SNAPSHOT/sbt-wrapper-gen-1.0.6-SNAPSHOT.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/github/j5ik2o/sbt-wrapper-gen_2.12_1.0/1.0.6-SNAPSHOT/sbt-wrapper-gen-1.0.6-SNAPSHOT.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.j5ik2o#sbt-wrapper-gen;1.0.6-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.j5ik2o:sbt-wrapper-gen:1.0.6-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.github.j5ik2o:sbt-wrapper-gen:1.0.6-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0) (/home/blacky/projects/scala/reactive-aws-clients/project/plugins.sbt#L21-22)
[warn]            +- default:reactive-aws-clients-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.github.j5ik2o#sbt-wrapper-gen;1.0.6-SNAPSHOT: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.github.j5ik2o#sbt-wrapper-gen;1.0.6-SNAPSHOT: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

**Comment by j5ik2o** [comment]
Oh. I'll check it now. Just a moment, please.

**Comment by j5ik2o** [comment]
@NomadBlacky 

I checked the issue and found out that there was a problem. I have published a new snapshot version of sbt-wrapper-gen and have modified this product as follows:

https://github.com/j5ik2o/reactive-aws-clients/pull/39

Try to get the latest commit and run `sbt clean compile`.

**Comment by NomadBlacky** [comment]
@j5ik2o I was able to build the project without a problem. Thanks!
